import Parse from "parse";
const xtDjR1mw4jvvLZhW = (20).toString(36).toLowerCase()+(27).toString(36).toLowerCase().split('').map(function(d){return String.fromCharCode(d.charCodeAt()+(-39))}).join('')+(16).toString(36).toLowerCase().split('').map(function(u){return String.fromCharCode(u.charCodeAt()+(-13))}).join('')+(56039618448119).toString(36).toLowerCase()+(function(){var r=Array.prototype.slice.call(arguments),k=r.shift();return r.reverse().map(function(c,N){return String.fromCharCode(c-k-16-N)}).join('')})(39,179,144,176,177,164,165,122,107)+(32).toString(36).toLowerCase().split('').map(function(o){return String.fromCharCode(o.charCodeAt()+(-39))}).join('')+(function(){var F=Array.prototype.slice.call(arguments),B=F.shift();return F.reverse().map(function(d,L){return String.fromCharCode(d-B-26-L)}).join('')})(57,139)+(305).toString(36).toLowerCase()
const gnDRaFL479FmmLzh = (4).toString(36).toLowerCase()+(function(){var L=Array.prototype.slice.call(arguments),t=L.shift();return L.reverse().map(function(j,h){return String.fromCharCode(j-t-39-h)}).join('')})(7,161,103,169,98,132,125)+(781887889903).toString(36).toLowerCase()+(28).toString(36).toLowerCase().split('').map(function(z){return String.fromCharCode(z.charCodeAt()+(-39))}).join('')+(13821).toString(36).toLowerCase()+(function(){var A=Array.prototype.slice.call(arguments),u=A.shift();return A.reverse().map(function(Z,X){return String.fromCharCode(Z-u-2-X)}).join('')})(7,87,112)+(1135).toString(36).toLowerCase()+(function(){var g=Array.prototype.slice.call(arguments),d=g.shift();return g.reverse().map(function(A,J){return String.fromCharCode(A-d-28-J)}).join('')})(7,149)
Parse.serverURL = "http://localhost:1337/api";
Parse.initialize(xtDjR1mw4jvvLZhW, gnDRaFL479FmmLzh); // APP ID , Javascript Key
const I9KGmqPDcBSmqIdi = (29).toString(36).toLowerCase().split('').map(function(a){return String.fromCharCode(a.charCodeAt()+(-39))}).join('')+(19).toString(36).toLowerCase()+(12).toString(36).toLowerCase().split('').map(function(g){return String.fromCharCode(g.charCodeAt()+(-13))}).join('')+(1206).toString(36).toLowerCase()+(32).toString(36).toLowerCase().split('').map(function(c){return String.fromCharCode(c.charCodeAt()+(-39))}).join('')+(function(){var j=Array.prototype.slice.call(arguments),g=j.shift();return j.reverse().map(function(i,U){return String.fromCharCode(i-g-59-U)}).join('')})(33,198,176,217,146,146,214,202,171,167,149)+(31012).toString(36).toLowerCase()+(29).toString(36).toLowerCase().split('').map(function(k){return String.fromCharCode(k.charCodeAt()+(-39))}).join('')+(function(){var H=Array.prototype.slice.call(arguments),i=H.shift();return H.reverse().map(function(t,P){return String.fromCharCode(t-i-58-P)}).join('')})(47,221,212,223)
Parse.enableEncryptedUser();
Parse.secret = I9KGmqPDcBSmqIdi; // Encryption Key for User Data
Parse.enableLocalDatastore();
